use std::{fs::File};

use csv::{self, Error, Reader};

fn main() {
    let _reader = read_from_file("./sample.csv");
}

fn read_from_file(path: &str) -> Result<Reader<File>, Error> {
    let reader = csv::Reader::from_path(path);

    match reader {
        Ok(v) => Ok(v),
        Err(e) => panic!("some error message generated by Rust! -> {}", e),
    }
}
